# DeviceTypes.py
#
# Author: DerekGn
#

DEVICE_TYPE_GENERAL = 243
DEVICE_TYPE_SWITCH = 244
DEVICE_TYPE_AIRQUALITY = 249
DEVICE_TYPE_TEMP_HUMIDITY = 82

DEVICE_SUB_TYPE_CUSTOM = 31
DEVICE_SUB_TYPE_COUNTER_INC = 28